// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: emails.sql

package database

import (
	"context"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (campaign_id, recipient_email)
VALUES ($1, $2)
RETURNING id, campaign_id, recipient_email, status, sent_at, created_at, updated_at
`

type CreateEmailParams struct {
	CampaignID     int32
	RecipientEmail string
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (Email, error) {
	row := q.db.QueryRowContext(ctx, createEmail, arg.CampaignID, arg.RecipientEmail)
	var i Email
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.RecipientEmail,
		&i.Status,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
