// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Campaign struct {
	ID          int32
	UserID      int32
	Name        string
	Subject     string
	Body        string
	ScheduledAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type CampaignOption struct {
	ID                    int32
	CampaignID            int32
	EnableGoogleAnalytics sql.NullBool
	UpdateProfileFormID   sql.NullInt32
	Tags                  pqtype.NullRawMessage
	Attachments           pqtype.NullRawMessage
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

type Email struct {
	ID             int32
	CampaignID     int32
	RecipientEmail string
	Status         sql.NullString
	SentAt         sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type EmailLog struct {
	ID        int32
	EmailID   int32
	Status    sql.NullString
	Message   sql.NullString
	CreatedAt sql.NullTime
}

type EmailTemplate struct {
	ID               int32
	UserID           int32
	TemplateName     string
	SubjectLine      string
	PreviewText      sql.NullString
	FromEmail        string
	FromName         string
	ReplyToEmail     sql.NullString
	CustomizeToField sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type Notification struct {
	ID        int32
	UserID    int32
	Message   string
	Read      sql.NullBool
	CreatedAt sql.NullTime
}

type Subscription struct {
	ID        int32
	UserID    int32
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        int32
	Email     string
	Password  string
	Name      string
	Verified  sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserProfile struct {
	ID            int32
	UserID        int32
	Email         string
	FirstName     string
	LastName      string
	PhoneNumber   sql.NullString
	CompanyName   string
	Website       sql.NullString
	StreetAddress string
	ZipCode       string
	City          string
	Country       string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
