// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Campaign struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Name        string
	Subject     string
	Body        string
	ScheduledAt sql.NullTime
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type CampaignOption struct {
	ID                    uuid.UUID
	CampaignID            uuid.UUID
	EnableGoogleAnalytics sql.NullBool
	UpdateProfileFormID   uuid.NullUUID
	Tags                  pqtype.NullRawMessage
	Attachments           pqtype.NullRawMessage
	CreatedAt             sql.NullTime
	UpdatedAt             sql.NullTime
}

type Email struct {
	ID             uuid.UUID
	CampaignID     uuid.UUID
	RecipientEmail string
	Status         sql.NullString
	SentAt         sql.NullTime
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}

type EmailLog struct {
	ID        uuid.UUID
	EmailID   uuid.UUID
	Status    sql.NullString
	Message   sql.NullString
	CreatedAt sql.NullTime
}

type EmailTemplate struct {
	ID               uuid.UUID
	UserID           uuid.UUID
	TemplateName     string
	SubjectLine      string
	PreviewText      sql.NullString
	FromEmail        string
	FromName         string
	ReplyToEmail     sql.NullString
	CustomizeToField sql.NullBool
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type EmailVerify struct {
	Email       string
	Code        string
	Retry       int32
	LastAttempt time.Time
}

type Notification struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Message   string
	Read      sql.NullBool
	CreatedAt sql.NullTime
}

type PasswordResetToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	CreatedAt sql.NullTime
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
}

type Subscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Email     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Name      string
	Verified  bool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserProfile struct {
	ID            uuid.UUID
	UserID        uuid.UUID
	Email         string
	FirstName     string
	LastName      string
	PhoneNumber   sql.NullString
	CompanyName   string
	Website       sql.NullString
	StreetAddress string
	ZipCode       string
	City          string
	Country       string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}
